stages:
  - checking
  - building

clang-format:
  stage: checking
  script:
    - git clone http://git.home.lan/root/check-clang-format.git
    - cp check-clang-format/check-clang-format.py .
    - python3 check-clang-format.py -r .

gcc:
  stage: building
  script:
    - ssh $SSH_USER@$VM_ADDRESS
      "rm -rf $CI_PROJECT_NAME &&
      git clone $CI_PROJECT_URL &&
      cd $CI_PROJECT_NAME &&
      mkdir build &&
      cd build &&
      cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release .. &&
      cmake --build . -j4"

clang:
  stage: building
  script:
    - ssh $SSH_USER@$VM_ADDRESS
      "rm -rf $CI_PROJECT_NAME &&
      git clone $CI_PROJECT_URL &&
      cd $CI_PROJECT_NAME &&
      mkdir build &&
      cd build &&
      cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release .. &&
      cmake --build . -j4"
